export const CASTES =  [
  "achari kongu vellala",
  "achari vishwakarma",
  "achari",
  "adi dravida paraya",
  "aentelur roman catholic",
  "ambattan",
  "arayan devara",
  "arayan",
  "barbar",
  "brahman bhatt",
  "brahman iyer",
  "brahman",
  "catholic latin catholic",
  "catholic pulaya",
  "catholic roman catholic",
  "catholic syrian",
  "catholic",
  "chakkiliyan amma",
  "chakkiliyan",
  "cheruman iraya",
  "cheruman kanakkan",
  "cheruman",
  "chettiar chakka",
  "chettiar telugu",
  "chettiar telugu chettiar",
  "chettiar vaniar",
  "chettiar",
  "christian catholic",
  "christian christian",
  "christian roman catholic",
  "christian",
  "dhobi",
  "dweepara",
  "ezhava ammelu",
  "ezhava chetti",
  "ezhava ezhava",
  "ezhava ghiyaiu",
  "ezhava harijan",
  "ezhava kongu vellala",
  "ezhava menon",
  "ezhava pankar",
  "ezhava pillai",
  "ezhava theyahan",
  "ezhava thiya",
  "ezhava vanika",
  "ezhava vaniyan",
  "ezhava varrer",
  "ezhava vathi",
  "ezhava",
  "ezhuthachan",
  "g.s.b.",
  "ganak",
  "gounder kongu vellala",
  "gounder menon",
  "gounder padaiyachi",
  "gounder pillai",
  "gounder vaniar",
  "gounder vellalar",
  "gounder",
  "gupthan",
  "hairua pillai",
  "harijan harijan",
  "harijan kollan",
  "harijan mannan",
  "harijan parayan",
  "harijan pulaya",
  "hindu nair",
  "hindu",
  "iyer",
  "jacobite syrian",
  "jacobite",
  "kallar",
  "kanakkan cheruman",
  "kanakkan syrian",
  "kanakkan",
  "knanaya cheduma",
  "knanaya chetti",
  "knanaya syrian",
  "knanaya",
  "kollan kadayan",
  "kollan",
  "koravan",
  "kudumbi",
  "kumbaran",
  "kurichian kurup",
  "kurichian",
  "mannadiyar tharakan",
  "mannadiyar",
  "mannan mannan",
  "mannan perumannan",
  "mannan",
  "mappilla assari",
  "mappilla mujahid",
  "mappilla",
  "mapthan",
  "maravar",
  "marthoma marthoma",
  "marthoma syrian",
  "marthoma",
  "moopar",
  "moosari",
  "moothan",
  "mudali",
  "mudaliyar kaikolan",
  "mudaliyar",
  "muslim jamamitk",
  "muslim jaman",
  "muslim jamari",
  "muslim mappilla",
  "muslim mujahid",
  "muslim muslim",
  "muslim rawther",
  "muslim sunni",
  "muslim",
  "muthunarayana",
  "nadar",
  "naicker kannar",
  "naicker kavadi",
  "naicker thotti",
  "naicker",
  "naik pillai",
  "naik veluthedu",
  "naik vilakithala",
  "nair bhattathi",
  "nair brahman",
  "nair chetti",
  "nair chettiar",
  "nair devara",
  "nair gupthan",
  "nair iyyangar",
  "nair kartha",
  "nair kurup",
  "nair marar",
  "nair menon",
  "nair nair",
  "nair nambiyar",
  "nair nambuthiri",
  "nair panickar",
  "nair pattar",
  "nair pentacostal",
  "nair picari",
  "nair pillai",
  "nair pothuwal",
  "nair roman catholic",
  "nair sunni",
  "nair syrian",
  "nair thiya",
  "nair vadiar",
  "nair valakathala",
  "nair variar",
  "nair vilakikrishnan",
  "nair vilakit",
  "nair vilakithala",
  "nair vllakiam",
  "nair",
  "nambudhiri",
  "nambudhiri namber dar",
  "nambudhiri namkar",
  "noprthaona syrian",
  "oddar",
  "orthodox jacobite",
  "orthodox roman catholic",
  "orthodox syrian",
  "paanan",
  "palaya harijan",
  "palaya mannon",
  "palaya pathiyan",
  "pandaram kongu vellala",
  "pandaram",
  "pandithar navidar",
  "pangaram",
  "panickar",
  "paniyan paniya",
  "paniyan",
  "para vannan",
  "paravan harijan",
  "paravan",
  "pentacostal cpm",
  "pentacostal latin catholic",
  "pentacostal pentacostal",
  "pentacostal roman catholic",
  "pentacostal syrian",
  "perkunna",
  "piniyar",
  "pisharodi",
  "poojari",
  "pulayan cheramar",
  "pulayan harijan",
  "pulayan mannan",
  "pulayan paravan",
  "pulayan pathiyan",
  "pulayan pulaya",
  "pulayan pulayan",
  "pulayan thiya",
  "pulayan vanikan",
  "pulayan",
  "pushpakan",
  "rakithar",
  "ranther",
  "routher",
  "syrian jacobite",
  "syrian",
  "thandan",
  "tharakan",
  "thattan thaman",
  "thattan thattan",
  "thevar akamudayar",
  "thevar",
  "thikodi cpm",
  "thiya namker",
  "thiya thiya",
  "thiyya",
  "vadukkar vaduka chetti",
  "vadukkar",
  "valan",
  "vanican",
  "varduka",
  "varriyar",
  "veduvar",
  "velan",
  "yadav thelagu",
  "yrakither",
  "akamudayar",
  "kongu vellala",
  "pulayan",
  "vishwakarma",
  "achari vishwakarma",
  "adidravida aravdur",
  "adidravida chalavadi",
  "adidravida harijan",
  "adidravida uppara",
  "adikarnataka chanaiahnatha",
  "adikarnataka gangemata",
  "adikarnataka gowndar",
  "adikarnataka halaki",
  "adikarnataka harijan",
  "adikarnataka holaya",
  "adikarnataka holer",
  "adikarnataka holeya",
  "adikarnataka holiya",
  "adikarnataka korama",
  "adikarnataka korur",
  "adikarnataka madiga",
  "adikarnataka medar",
  "adikarnataka mochi",
  "adikarnataka muggudavar",
  "aganarw kamared",
  "agasa agasa",
  "agasa dobi",
  "ambiga ambigar",
  "badigar vishwakarma",
  "bajantri bajantri",
  "bajantri kshwrika",
  "balagiga balagiga",
  "balagiga sunnakail",
  "baligar baligar",
  "baman samrath",
  "baniya baniya",
  "banjara banjara",
  "bavasar bavasar",
  "bavasarkshatriya darje",
  "bedar bedar",
  "bedar bepar",
  "belavva pujari",
  "bestha mogeru",
  "bestha pujari",
  "bhajantri bhajantri",
  "bhandari kshwrika",
  "bhandari naik",
  "bhovi dasarli",
  "bhovi gangemata",
  "bhovi vadda",
  "bhovi varddar",
  "bhovi wadda",
  "billava pujari",
  "brahman ajer",
  "brahman hauyak",
  "brahman havasala",
  "brahman havjak",
  "brahman havyaka",
  "brahman iyangar",
  "brahman kotta",
  "brahman samrath",
  "brahman vaishnav",
  "christian catholic",
  "christian protestant",
  "christian roman",
  "christian",
  "cugayat kumber",
  "danatar danatar",
  "dasaru",
  "davar davar",
  "devangashetty dasayia",
  "dobi dobi",
  "dora dora",
  "dravida catholic",
  "dwar dwar",
  "gangemata mogeru",
  "ganiga ganiga",
  "ganiga sheety",
  "ganiga",
  "ganiger ganiga",
  "ganiger ganiger",
  "godali godali",
  "gonday gonday",
  "gondhali gondhali",
  "gondhali goudali",
  "gowda kshwrika",
  "gowda nama",
  "gowda vokkaliga",
  "gurav gurav",
  "halakki hakkipekki",
  "hanabar hajabar",
  "hanabar hanabar",
  "harer harayal",
  "harijan harijan",
  "harijan ranger",
  "helawar helawar",
  "hindukrubi halamatha",
  "hindulingayat panchamsali",
  "holaya chaluvadi",
  "holer holer",
  "holeya adikarnataka",
  "idiga gowdru",
  "idiga naik",
  "idiga najak",
  "idiga pujari",
  "idiga talwar",
  "igola igola",
  "iliger iliger",
  "jain bogar",
  "jain digambar",
  "jain swetambar",
  "janwakar janwakar",
  "jogi balegara",
  "kabbou kabbou",
  "kadanpatadar kapavpayr",
  "kalal kalal",
  "kambar kambar",
  "kanabar kanabar",
  "kashaty naik",
  "kihatayera naik",
  "kisrubar halamatha",
  "koli koli",
  "korama korama",
  "koravaru kparau",
  "korawar korawar",
  "korawar kuravar",
  "korma korma",
  "kristan kristan",
  "kshatriya arer",
  "kshatriya kshatriya",
  "kshatriya maratha",
  "kshatriya naik",
  "kshatriya pateear",
  "kulubar halamatha",
  "kumbara kumbara",
  "kumbara",
  "kumrar kulal",
  "kurava halamatha",
  "kuruba balagar",
  "kuruba durubar",
  "kuruba gangemata",
  "kuruba halabar",
  "kuruba halamatha",
  "kuruba halma",
  "kuruba kumbar",
  "kuruba panchamsali",
  "kuruba",
  "lambani lambani",
  "lingayat anchal",
  "lingayat badiger",
  "lingayat banagar",
  "lingayat banajiga",
  "lingayat brahman",
  "lingayat devanga",
  "lingayat gangemata",
  "lingayat ganiga",
  "lingayat ganti",
  "lingayat ghani",
  "lingayat godar",
  "lingayat gouda",
  "lingayat goudar",
  "lingayat gowda",
  "lingayat halamatha",
  "lingayat hugar",
  "lingayat jad",
  "lingayat jangama",
  "lingayat kambar",
  "lingayat kumar",
  "lingayat kumbar",
  "lingayat kumbara",
  "lingayat madiwal",
  "lingayat malagowda",
  "lingayat malgar",
  "lingayat mulla",
  "lingayat musugu",
  "lingayat nanabaur",
  "lingayat navi",
  "lingayat nonabaru",
  "lingayat okkaliga",
  "lingayat panachasil",
  "lingayat pancahnash",
  "lingayat panchalmali",
  "lingayat panchaluppar",
  "lingayat panchamsali",
  "lingayat panchan",
  "lingayat panchanan",
  "lingayat panchnaht",
  "lingayat pandhal",
  "lingayat pattar",
  "lingayat phangamasali",
  "lingayat punchal",
  "lingayat reddy",
  "lingayat sadaru",
  "lingayat sadujang",
  "lingayat saduran",
  "lingayat samagar",
  "lingayat samarta",
  "lingayat samrath",
  "lingayat setti",
  "lingayat sheety",
  "lingayat shetty",
  "lingayat shimpi",
  "lingayat simpi",
  "lingayat sindi",
  "lingayat songar",
  "lingayat sunagar",
  "lingayat swami",
  "lingayat veershaiva",
  "lingayat vokkaliga",
  "maatauppar kshatriya",
  "madat arer",
  "madat lingayat",
  "madat rear",
  "madduala agasa",
  "madevashashetty agasa",
  "madhivala agasa",
  "madiga asalaru",
  "madiga hasalaru",
  "madiga kshatriya",
  "madiga madiga",
  "madiga talwar",
  "madivala agasa",
  "madivalashetty agasa",
  "madiwal agasa",
  "mahali bhandari",
  "malagar malgar",
  "malakar malakar",
  "maleyali idiga",
  "malgar malgar",
  "marahovi gangemata",
  "maratha adayr",
  "maratha araertha",
  "maratha arer",
  "maratha bailkamber",
  "maratha golla",
  "maratha kihyata",
  "maratha kshatriya",
  "maratha kunbi",
  "maratha maratha",
  "maratha shivaji",
  "maratha shivajiya",
  "maratha simpi",
  "maratha",
  "maraya arer",
  "maraya samrath",
  "marivala agasa",
  "medar madiga",
  "medar medar",
  "medar swetambar",
  "muslim byare",
  "muslim medar",
  "muslim mulla",
  "muslim muslim",
  "muslim nadaf",
  "muslim nadag",
  "muslim nadak",
  "muslim nadar",
  "muslim napae",
  "muslim panchamsali",
  "muslim pathan",
  "muslim samrath",
  "muslim sayed",
  "muslim sheikh",
  "muslim sunni",
  "muslim swetambar",
  "muslim swnnr",
  "muslim wade",
  "muslim",
  "nadar nadar",
  "nadavar nadavar",
  "naik idiga",
  "naik naik",
  "naik namdari",
  "namdari naik",
  "namdev namdev",
  "navi hadapad",
  "navi navi",
  "nayaka naidu",
  "nayaka namdari",
  "nayaka nayak",
  "nayaka talwar",
  "nayaka valmiki",
  "nayaka",
  "nayanakbhirya bhandari",
  "nayanakshathriyyan naveda",
  "nayankshatriya barbar",
  "naynakishthraja hajama",
  "palegara najak",
  "panchal panchamsali",
  "patidar patidar",
  "pinjar pinjar",
  "pinjar",
  "pujeri pujari",
  "rajput rajawan",
  "rajput rajput",
  "rajput singh",
  "reddy kamma",
  "reddy paknak",
  "reddy reddy",
  "roman catholic",
  "romancatholik catholic",
  "s.siddaru s.siddaru",
  "samagar samagar",
  "samagar sampagar",
  "samdigya samdigya",
  "shetty banajiga",
  "shetty dayavagnabhramana",
  "shetty devanga",
  "shetty dyavagna",
  "shetty ganiga",
  "shetty kumbara",
  "shetty nadal",
  "shetty nadava",
  "shetty pujari",
  "siddri",
  "sirian",
  "sudigadusiddha sudigadusiddau",
  "sunagar sunagar",
  "sunni samrath",
  "swamyagol swamyagol",
  "swnagar swangar",
  "tamilivas gowndar",
  "tamilu gowndar",
  "telugu telugu",
  "uddar swetambar",
  "uddar uddar",
  "uddar uppalag",
  "uddar uppar",
  "uppara uppara",
  "vaddaru kalluvaddaru",
  "valmiki talwar",
  "vddar vadda",
  "veershiv jangama",
  "vishwakarma achari",
  "vokkaliga achar",
  "vokkaliga achari",
  "vokkaliga gangadkar",
  "vokkaliga gangatikar",
  "vokkaliga gowda",
  "vokkaliga kurubagowda",
  "vokkaliga musukagowda",
  "vokkaliga reddy",
  "vokkaliga vamdadi",
  "vokkaliga vishwakarma",
  "wadar vadda",
  "waddar wadda",
  "waddar waddar",
  "waddar wader",
  "wadeyar wadeyar",
  "walikar walikar",
  "yadav golla",
  "yishas sheety",
  "others",
  "baniya powar",
  "banjara gormati",
  "bari",
  "berad",
  "bhoep",
  "brahman brahman",
  "brahman deshastha",
  "brahman krushmapakshi",
  "brahman mohabrahman",
  "brahman pardesi",
  "buddha",
  "burud",
  "chambhar pardesi",
  "chambhar telangi",
  "chambhar",
  "dhangar hatkar",
  "dhangar shegar",
  "dhangar",
  "dhiwar bendor",
  "dhiwar bhahare",
  "dhiwar bhanare",
  "dhiwar bhandare",
  "dhiwar zade",
  "dhiwar",
  "dhobi dhobi",
  "dhobi",
  "dombari",
  "gandali telangi",
  "gandali",
  "gavali hanwar",
  "gavali krishna",
  "gavali kurshna",
  "gavali nand",
  "gavali",
  "golkar",
  "gond gavani",
  "gond mana",
  "gond naikepade",
  "gond rajgond",
  "gond satdeve",
  "gond shahdeve",
  "gond",
  "govind",
  "gowari adiwasi",
  "gowari bawne",
  "gowari bhanare",
  "gowari dhudha",
  "gowari dudhgonari",
  "gowari dudhgowali",
  "gowari gadilohar",
  "gowari gowari",
  "gowari kasu",
  "gowari",
  "gurav gurav",
  "gurav",
  "hanber",
  "holar",
  "holi",
  "jain digambar",
  "jain gurjar",
  "jain swetambar",
  "jain",
  "kaikadi",
  "kalar jain",
  "kalar jainkalar",
  "kalar kalar",
  "kalar zade",
  "karvi",
  "kohali bhelikhaye",
  "kolam",
  "koli mahadevkoli",
  "koli malharkoli",
  "koli",
  "korku korku",
  "korku",
  "koshti garewal",
  "koshti kalba",
  "koshti",
  "kumbi khaire",
  "kumbi khedule",
  "kumhar kumbhar",
  "kumhar rane",
  "kumhar",
  "kunbi bawne",
  "kunbi dobaile",
  "kunbi garewal",
  "kunbi khaire",
  "kunbi khedule",
  "kunbi mana",
  "kunbi padimshali",
  "kunbi rane",
  "kunbi tirele",
  "kunbi zade",
  "kunbi",
  "laman",
  "lingayat chaturth",
  "lingayat navi",
  "lingayat pancham",
  "lingayat wani",
  "lingayat",
  "lodhi chatri",
  "lodhi jagade",
  "lodhi jangade",
  "lodhi",
  "lohar chatri",
  "lohar gadilohar",
  "lohar jagade",
  "lohar panchal",
  "lohar wadhai",
  "lohar",
  "mahar barke",
  "mahar bawne",
  "mahar bhale",
  "mahar kosare",
  "mahar mahar",
  "mahar",
  "mali kosare",
  "mali mali",
  "mali phulmali",
  "mali thakur",
  "mali zade",
  "mali",
  "mana gadilohar",
  "mana mana",
  "mana",
  "mang",
  "manne",
  "maratha chaturth",
  "maratha kunbi",
  "maratha mali",
  "maratha maratha",
  "maratha shegar",
  "maratha",
  "marwadi",
  "matang matang",
  "matang shegar",
  "matang",
  "mavi powar",
  "muslim muslim",
  "muslim sayed",
  "muslim shaikh",
  "muslim",
  "nathjogi",
  "nhavi zade",
  "nhavi",
  "panchal chaturth",
  "panchal sutar",
  "pardesi chatri",
  "pardi pardi",
  "parit parit",
  "parit",
  "pathan",
  "pawar chatri",
  "pinjara",
  "powar powar",
  "powar",
  "pradhan",
  "rajput bhamta",
  "rajput rajput",
  "ramoshi",
  "sayed",
  "shikaghar",
  "shimpi namdev",
  "shimpi shimpi",
  "sonar chatri",
  "sonar maratha",
  "sonar zade",
  "sonar",
  "sutar loharsutar",
  "sutar panchal",
  "sutar sutar",
  "sutar zade",
  "sutar",
  "teli baile",
  "teli bawne",
  "teli dobaile",
  "teli ekbaile",
  "teli jainkalar",
  "teli kosare",
  "teli",
  "vani",
  "wadar",
  "wadhi",
  "wami",
  "wathi",
  "ahir soratha",
  "ahir",
  "ansari",
  "anvil brahmin",
  "atit bayaji bakshi panch",
  "bajaniya",
  "bajir",
  "bakshi",
  "bakshi panch barot",
  "bakshi panch bavaji",
  "bakshi panch nodi",
  "bakshi panch sameja",
  "bakshi panch vanand",
  "bakshi panch",
  "baphan",
  "bauliya",
  "bavaji gosawmi",
  "bavaji nath",
  "bavaji nimavat",
  "bavaji",
  "bawa bakshi panch",
  "bawa",
  "bawaji bakshi panch",
  "bawaji gosawmi",
  "bhajir",
  "bhakta",
  "bhangi bakshi panch",
  "bhangi",
  "bhanushail kachhi",
  "bharvad chotabhai",
  "bharvad goltar",
  "bharvad lakha",
  "bharvad mota bhai",
  "bharvad",
  "bhatti",
  "bhil",
  "brahmin adhit",
  "brahmin bakshi panch",
  "brahmin gosawmi",
  "brahmin kutchhi",
  "brahmin nayak",
  "brahmin prajapati",
  "brahmin pujari",
  "brahmin rajgor",
  "brahmin saraswati",
  "brahmin swami",
  "brahmin tapodhan",
  "brahmin thakur",
  "brahmin vishvas",
  "brahmin",
  "brahmin",
  "chake",
  "chamar kholi",
  "chamar parmar",
  "chamar",
  "choudhari",
  "chunara",
  "darbar garasiya",
  "darbar kathi",
  "darbar kholi",
  "darbar rajput",
  "darbar",
  "darji modh",
  "darji",
  "dasnami vawa gira",
  "devipujak",
  "dhobi",
  "dhodia patel",
  "dhoka",
  "gadhavi brahmin",
  "gadhavi maru",
  "galiara makavana",
  "gamit",
  "garoda bakshi panch",
  "gaur brahmin",
  "gaur",
  "goai",
  "gohil",
  "goswami vairagi",
  "gujara gohil",
  "gujara jadav",
  "gujara maheshwari",
  "gujara parmar",
  "gujara",
  "hajam vankar",
  "halpati",
  "harijan bakshi panch",
  "harijan chamar",
  "harijan jadav",
  "harijan marvadi",
  "harijan parmar",
  "harijan vankar",
  "harijan",
  "hindu halpati",
  "hindu kumbhar maru",
  "hindu kumbhar",
  "jadeja darbar",
  "jain pitambar",
  "jat bhatti",
  "jat",
  "kadwa",
  "kalaria",
  "kathlik",
  "kever",
  "khalifa",
  "khodi suvadiya",
  "khodi",
  "kohli patel",
  "kohli soratha",
  "kohli suvadiya",
  "kohli talpada",
  "kohli",
  "kotvaliya",
  "kshatriya chauhan",
  "kshatriya parmar",
  "kshatriya rathod",
  "kshatriya thakur",
  "kshatriya",
  "kumbhar bhalgama",
  "kumbhar prajapati",
  "kumbhar",
  "lohana kutchhi",
  "lohana thakur",
  "lohana",
  "lohar bakshi panch",
  "lohar gohil",
  "lohar panchai",
  "lohar",
  "mahar leva",
  "mahar",
  "mahiyavanshi",
  "maisurba vanand",
  "maiya darbar phdheriya",
  "makvana",
  "maldhari kholi",
  "maldhari rabari",
  "maldhari",
  "malik sayyad",
  "malik vajir",
  "malik",
  "malwana",
  "mansur",
  "maratha karadiya",
  "maratha rathod",
  "maratha",
  "mavadi",
  "mayka",
  "mer",
  "mistri varu",
  "mistri",
  "mochi",
  "momin",
  "nat",
  "natiar",
  "nayak bhavana",
  "nayak rathod",
  "nayak",
  "nepal",
  "nishad kevad",
  "nishad machi",
  "panchal",
  "pandya",
  "pardhi",
  "parjiyat",
  "parmar chamar",
  "parmar darji",
  "parmar",
  "patel khodi",
  "patel leuva",
  "patel leva",
  "patel kadav",
  "patel karadiya",
  "patel",
  "pathan",
  "patil leva",
  "patil kadva",
  "patil karadiya",
  "patil",
  "pinjara bakshi panch",
  "pinjara",
  "prajapati bhalgama",
  "prajapati patadiya",
  "prajapati",
  "rabari bakshi panch",
  "rabari gujjar",
  "rabari rayaka",
  "rabari",
  "rajput bhalaiya",
  "rajput chauhan",
  "rajput jadav",
  "rajput khodi",
  "rajput leva",
  "rajput nadoda",
  "rajput parmar",
  "rajput rathvi",
  "rajput vaghela",
  "rajput karadiya",
  "rajput",
  "rathod",
  "rathwa kholi",
  "rathwa tadvi",
  "raval",
  "sadhu",
  "sadhu",
  "sadhu",
  "saha",
  "sama",
  "samma",
  "sanghar",
  "sanghi",
  "sathawara dalyadi",
  "sathawara kholi",
  "sathawara",
  "sheikh",
  "shipai juneja",
  "shipai",
  "shuthar bakshi panch",
  "shuthar kadva",
  "siddiqui",
  "ochra brahmin",
  "solanki",
  "soni prajapati",
  "soni kansar",
  "soni parajiyat",
  "soni",
  "srimani",
  "suthar kumbhar",
  "suthar marvadi",
  "suthar",
  "suthar",
  "tadvi",
  "tailor",
  "taldada devipujak",
  "taldada kholi",
  "taldada",
  "thakarda",
  "thakur",
  "tholiya",
  "vadi",
  "vaghari devipujak",
  "vaghari kholi",
  "vaghari",
  "vaghela",
  "vairangi bawa",
  "vaisnav",
  "vanad odhaviya",
  "vanad",
  "vanakar bakshi panch",
  "vanakar mota bhai",
  "vanakar",
  "vanand bakshi panch",
  "vanand chokh",
  "vanand maheshwari",
  "vanand soratha",
  "vanand",
  "vanandvas",
  "vania maheshwari",
  "vania vaisnav",
  "vania",
  "vora",
  "vyash brahmin",
  "waghri",
  "babariya",
  "bhajir",
  "kumbhar",
  "lakha",
  "nodi",
  "pinjara",
  "sama",
  "tholiya",
  "khalifa",
  "shoda",
  "adiwasi bhilala",
  "adiwasi khan",
  "ahir aske",
  "ahir bagde",
  "ahir jamre",
  "ahir khanna",
  "ahir lalharia",
  "ahir narnavre",
  "ahir sonwani",
  "ahir wanjare",
  "ahir yadav",
  "badhai",
  "baniya asrati",
  "baniya gupta",
  "baniya keshrwani",
  "baniya khandel",
  "baniya sahu",
  "banjara chadawa",
  "banjara chandwar",
  "banjara khan",
  "banjara rathor",
  "banjara",
  "barhai malvia",
  "barhai sharma",
  "barhai vishwakarma",
  "bashor bansal",
  "bashor basor",
  "bashor",
  "beldar bhati",
  "beldar tawar",
  "bharud dhangar",
  "bharud dhankar",
  "bharud yadav",
  "bhilala akoliya",
  "bhilala aske",
  "bhilala awase",
  "bhilala baddle",
  "bhilala baghel",
  "bhilala bakauley",
  "bhilala balkey",
  "bhilala bhage",
  "bhilala bhel",
  "bhilala bhew",
  "bhilala bhuriya",
  "bhilala chauhan",
  "bhilala chongar",
  "bhilala damar",
  "bhilala darbar",
  "bhilala dhile",
  "bhilala dodwal",
  "bhilala dorwar",
  "bhilala dwar",
  "bhilala gangwal",
  "bhilala gore",
  "bhilala gwale",
  "bhilala jamre",
  "bhilala jhhila",
  "bhilala jilve",
  "bhilala kanashe",
  "bhilala khanna",
  "bhilala kharte",
  "bhilala khatiya",
  "bhilala kolh",
  "bhilala kushwaha",
  "bhilala malvia",
  "bhilala mandoli",
  "bhilala mankoli",
  "bhilala mori",
  "bhilala mozalda",
  "bhilala mudalje",
  "bhilala mukatib",
  "bhilala nargave",
  "bhilala nargesh",
  "bhilala nihal",
  "bhilala ningwal",
  "bhilala rathor",
  "bhilala rawat",
  "bhilala romdade",
  "bhilala saitey",
  "bhilala setia",
  "bhilala shaite",
  "bhilala solanki",
  "bhilala sonar",
  "bhilala tadwla",
  "bhilala varman",
  "bhilala wage",
  "bhilala waskale",
  "bhilala yadav",
  "bhilala",
  "bhujwa verma",
  "binjwar meshram",
  "brahman besnab",
  "brahman bhargav",
  "brahman chaturvedi",
  "brahman dixit",
  "brahman dwivedi",
  "brahman mishra",
  "brahman pandey",
  "brahman sharma",
  "brahman shukla",
  "brahman tiwari",
  "brahman tripathi",
  "brahman trivedi",
  "brahman upadhyay",
  "brahman vaishnav",
  "brahman vyas",
  "chamar ahirwar",
  "chamar baalai",
  "chamar bakauley",
  "chamar balai",
  "chamar banjara",
  "chamar basor",
  "chamar bhalse",
  "chamar borkar",
  "chamar chauhan",
  "chamar choudhary",
  "chamar fune",
  "chamar garg",
  "chamar kanoji",
  "chamar kobragaday",
  "chamar mahar",
  "chamar makasiya",
  "chamar mehra",
  "chamar meshram",
  "chamar mishra",
  "chamar mozalda",
  "chamar raidas",
  "chamar ramteke",
  "chamar sahare",
  "chamar saket",
  "chamar solanki",
  "chamar sunteke",
  "chamar suryavanshi",
  "chamar wanjare",
  "chamar",
  "darji namdeo",
  "dhimar dogarwar",
  "dhimar kamare",
  "dhimar kamday",
  "dhimar meshram",
  "dhimar morde",
  "dhimar",
  "dhobi kelde",
  "dhobi varetha",
  "dhobi",
  "dosandhi raoji",
  "fakir khan",
  "fakir shah",
  "gadariya pal",
  "gadariya",
  "gond kumre",
  "gowala bhandar",
  "gowala chouda",
  "gowala choudhary",
  "gowala koru",
  "gowala newari",
  "gowala phune",
  "gowari kohare",
  "gowari newari",
  "gujjar patel",
  "julaha ali",
  "kachhi kushwaha",
  "kachhi patel",
  "kahar barua",
  "kahar japta",
  "kahar orma",
  "kahar patwa",
  "kahar verma",
  "kahar",
  "kalar dashare",
  "kalar deshmukh",
  "kalar kawde",
  "kalar meshram",
  "kalar patlay",
  "kalar rao",
  "kalar share",
  "kalar sinde",
  "kalwar jaiswal",
  "kewat bhargav",
  "kewat navada",
  "kewat nishad",
  "kewat",
  "koeri maurya",
  "koeri morya",
  "kol rawat",
  "kol",
  "kolwar jaiswal",
  "kolwar jamre",
  "kori",
  "kshatriya banafar",
  "kshatriya chauhan",
  "kshatriya darbar",
  "kshatriya kewra",
  "kshatriya raghuwansi",
  "kshatriya solanki",
  "kshatriya sonar",
  "kshatriya suryavanshi",
  "kud idpachi",
  "kud patar",
  "kumhar bagwa",
  "kumhar chakradhari",
  "kumhar chitway",
  "kumhar kokde",
  "kumhar paday",
  "kumhar prajapati",
  "kumhar snichara",
  "kumhar telashu",
  "kumhar tilasho",
  "kurmi bagde",
  "kurmi baikar",
  "kurmi brahman",
  "kurmi chature",
  "kurmi chutal",
  "kurmi dogarwar",
  "kurmi doye",
  "kurmi funde",
  "kurmi hathimare",
  "kurmi mahar",
  "kurmi maharbar",
  "kurmi munde",
  "kurmi patel",
  "kurmi pathodi",
  "kurmi punde",
  "kurmi rao",
  "kurmi shivakar",
  "kurmi sivankar",
  "kurmi ughar",
  "lakhera",
  "lodhi baithwal",
  "lodhi banoth",
  "lodhi banwate",
  "lodhi basone",
  "lodhi bhaghare",
  "lodhi chutal",
  "lodhi damahal",
  "lodhi damair",
  "lodhi dashare",
  "lodhi dashariya",
  "lodhi dhahare",
  "lodhi giriya",
  "lodhi jangda",
  "lodhi kurahi",
  "lodhi lilahar",
  "lodhi machandar",
  "lodhi machhirke",
  "lodhi mashchy",
  "lodhi mashkare",
  "lodhi mawle",
  "lodhi nagpuri",
  "lodhi pamahea",
  "lodhi ratule",
  "lodhi sahare",
  "lodhi singh",
  "lodhi thakre",
  "lodhi verma",
  "lohar bawri",
  "lohar sonwani",
  "lohar verma",
  "lohar vishwakarma",
  "lohar yadav",
  "mahar baddle",
  "mahar borkar",
  "mahar jambhudkar",
  "mahar mashkare",
  "mahar rauth",
  "mahar sahare",
  "mahar sakare",
  "mahar tudpada",
  "mahar walde",
  "mahar wanjare",
  "maithare maithare",
  "mali saini",
  "mana mankar",
  "mana narnavre",
  "mankar manthakur",
  "mankar nihal",
  "mankar saitey",
  "mansuri khan",
  "methar mathar",
  "mominansari ansari",
  "mominansari julaha",
  "mushar",
  "nai ben",
  "nai khawasi",
  "nai pagade",
  "nai sen",
  "nai thakur",
  "nai verma",
  "nai",
  "namdev",
  "pasi paswan",
  "pathan bhage",
  "pathan khan",
  "pathan solanki",
  "powar katre",
  "powar patlay",
  "powar temre",
  "powar thakre",
  "rajput chauhan",
  "savarkar fahye",
  "savarkar mashki",
  "sirvi barfa",
  "sirvi choyal",
  "sirvi devda",
  "sirvi gahlot",
  "sirvi kag",
  "sirvi lacheta",
  "sirvi mulewa",
  "sirvi parihar",
  "sirvi pawar",
  "sirvi rathor",
  "sirvi septa",
  "sonar kurve",
  "sonar soni",
  "sonar",
  "soni soni",
  "sundi gupta",
  "tamar",
  "teli bogada",
  "teli chandra",
  "teli giripunje",
  "teli karenjeka",
  "teli karnjkar",
  "teli rathor",
  "teli sahu",
  "teli sharma",
  "teli",
  "others",
  "agarawal agarawal",
  "agarawal mahajan",
  "agarawal paliwal",
  "agarawal singhal",
  "agarawal",
  "ahir gurjar",
  "ahir kumawat",
  "ahir paliwal",
  "ahir rathore",
  "ahir sisodia",
  "ahir yadav",
  "ahir",
  "arora batra",
  "arora",
  "bagri",
  "bairagi rathore",
  "bairagi",
  "baishnoi",
  "banjara gametia",
  "banjara kumawat",
  "banjara mansuri",
  "banjara nayak",
  "banjara rangrez",
  "banjara ravana",
  "banjara vaishnav",
  "banjara",
  "banwari",
  "baori baori",
  "baori choukida",
  "baori",
  "bari",
  "bhanbhuniya",
  "bhand",
  "bharbhooja kachchi",
  "bharbhooja mathuriya",
  "bharbhooja",
  "bhil gametia",
  "bhil meena",
  "bhil",
  "bhoru",
  "bishnoi",
  "bohra",
  "brahman audich",
  "brahman dadhich",
  "brahman gaur",
  "brahman gautam",
  "brahman joshi",
  "brahman kaushik",
  "brahman mahajan",
  "brahman paliwal",
  "brahman pareek",
  "brahman porasa",
  "brahman purohit",
  "brahman rajpurohit",
  "brahman saraswat",
  "brahman sharma",
  "brahman soni",
  "brahman tiwari",
  "brahman upadhayay",
  "brahman vyas",
  "brahman",
  "bunkar",
  "chamar balaji",
  "chamar balmiki",
  "chamar baori",
  "chamar berwa",
  "chamar dhanka",
  "chamar dhankar",
  "chamar gametia",
  "chamar harijan",
  "chamar jatav",
  "chamar khati",
  "chamar kumawat",
  "chamar meghwal",
  "chamar mehatar",
  "chamar mehra",
  "chamar nayak",
  "chamar raigar",
  "chamar",
  "chanthi",
  "chippa",
  "christian",
  "darji meghwal",
  "darji rathore",
  "darji",
  "dewasi",
  "dhakar swami",
  "dhakar",
  "dhali",
  "dhanka",
  "dhobi ravana",
  "dhobi",
  "dholi gaur",
  "dholi khati",
  "dholi meghwal",
  "dholi pawar",
  "dholi",
  "faqir",
  "gadaria pal",
  "gadaria",
  "gadialohar",
  "garua gaur",
  "gawariya",
  "ghachha",
  "ghachi mewad",
  "ghachi ravana",
  "ghachi",
  "girui",
  "gosai giri",
  "goswami giri",
  "gurjar",
  "harijan balmiki",
  "jaga",
  "jain mahajan",
  "jain paliwal",
  "jain",
  "jambuli",
  "jat chauhan",
  "jat dhankar",
  "jat rathore",
  "jat sheoran",
  "jat",
  "jingar jatav",
  "jingar",
  "julaha ansari",
  "kahar kashyap",
  "kahar",
  "kakhera",
  "kalal kalal",
  "kalal mewad",
  "kalal ravana",
  "kalal",
  "kalbeliya",
  "kali mahavar",
  "kandera",
  "kayasth mathar",
  "kayasth mathu",
  "kayasth saxena",
  "khandelwal",
  "khatik chauhan",
  "khatik gaur",
  "khatik yadav",
  "khatik",
  "khatri goyal",
  "koli mahavar",
  "kumhar jalandhar",
  "kumhar kumawat",
  "lakhara chauhan",
  "lakhara",
  "lohar kumawat",
  "lohar paliwal",
  "lohar vishwakarma",
  "lohar yadav",
  "lohar",
  "maheshwari joshi",
  "maheshwari mahajan",
  "maheshwari",
  "mali bhoi",
  "mali gametia",
  "mali kachchi",
  "mali phulmali",
  "mali saini",
  "malik",
  "mazabi",
  "mehar",
  "mirasi",
  "mirza",
  "mughal beg",
  "mughal joshi",
  "mughal meena",
  "mughal rathore",
  "mughal",
  "muslim qureshi",
  "nai dhanka",
  "nai dhankar",
  "nai mahajan",
  "nai rathore",
  "nai saini",
  "nai yadav",
  "nai",
  "nath nathyogi",
  "nath swami",
  "nath",
  "nayak chamar",
  "nilgar gametia",
  "nilgar jatav",
  "nilgar",
  "parsi",
  "patel",
  "pathan bhati",
  "pathan goyal",
  "pathan jatav",
  "pathan khan",
  "pathan leelgar",
  "pathan meena",
  "pathan mewad",
  "pathan mirza",
  "pathan panwar",
  "pathan pawar",
  "pathan raigar",
  "pathan ravana",
  "pathan",
  "phanka",
  "puri",
  "rabari",
  "rajput bhati",
  "rajput bholi",
  "rajput chandawat",
  "rajput chandra",
  "rajput chauhan",
  "rajput daraga",
  "rajput deval",
  "rajput devra",
  "rajput gaur",
  "rajput jhala",
  "rajput joshi",
  "rajput khandera",
  "rajput kharal",
  "rajput meena",
  "rajput palihar",
  "rajput panwar",
  "rajput pawar",
  "rajput rahtore",
  "rajput ranawat",
  "rajput rao",
  "rajput rathore",
  "rajput ravana",
  "rajput rawat",
  "rajput sarang",
  "rajput shekhawat",
  "rajput singh",
  "rajput sisodia",
  "rajput solanki",
  "rajput tanwar",
  "rajput",
  "rama rao",
  "rana bhati",
  "rana mali",
  "rana rana",
  "rana vaishnav",
  "rana",
  "rana",
  "rao mansuri",
  "rao",
  "sadh khati",
  "sadh swami",
  "sadh vaishnav",
  "sadh",
  "sainibrahman dakot",
  "sainibrahman dalot",
  "salvi mehatar",
  "salvi",
  "samar soni",
  "sansi",
  "saragara yuresi",
  "saragara",
  "saryan",
  "sasui qureshi",
  "sayed kadri",
  "sayed",
  "sheikh beg",
  "sheikh khan",
  "sheikh raigar",
  "sheikh",
  "sikh jatav",
  "sikh",
  "sindhi",
  "sirvi",
  "sunar soni",
  "sunar",
  "suthar khati",
  "suthar saxena",
  "suthar soni",
  "suthar",
  "tamboli",
  "tank",
  "teli rathore",
  "teli",
  "others",
  "acharya prajapati",
  "ahir yadav",
  "arora chhabra",
  "arora chopra",
  "arora chugh",
  "arora gulati",
  "arora kapoor",
  "arora kathuriya",
  "arora khatri",
  "arora minocha",
  "arora nagpal",
  "arora panghal",
  "arora rai",
  "arora thakral",
  "badai harijan",
  "badai jangada",
  "badai",
  "bairagi gill",
  "bairagi powar",
  "bairagi swami",
  "bairagi",
  "balmiki bhangi",
  "balmiki",
  "baniya agarwal",
  "baniya arora",
  "baniya bansal",
  "baniya garg",
  "baniya goyal",
  "baniya gupta",
  "baniya jain",
  "baniya jindal",
  "baniya kansal",
  "baniya mahajan",
  "baniya rana",
  "baniya shahu",
  "baniya singla",
  "baniya",
  "bannsa garg",
  "baori",
  "barhai dhiman",
  "barhai garg",
  "barhai khati",
  "barhai sharma",
  "barhai vishwakarma",
  "bawaria dabla",
  "bazigar badhai",
  "bhat acharya",
  "bhat sharma",
  "brahaman sharma",
  "brahiman sharma",
  "brahman acharya",
  "brahman gaur",
  "brahman kaushik",
  "brahman sandilya",
  "brahman sanyal",
  "brahman sharma",
  "brahman shrma",
  "brahman vassist",
  "brahman vyas",
  "brhamin sharma",
  "chamar bavariya",
  "chamar dhanak",
  "chamar harijan",
  "chamar kashyap",
  "chamar kori",
  "chamar nayak",
  "chamar ramdasi",
  "chamar ravi",
  "chamar ravidas",
  "chamar ravidasi",
  "chamar",
  "chhimbe darji",
  "chhimbe verma",
  "chhipi darji",
  "chhipi harijan",
  "chhipi lilgar",
  "chhipi manihar",
  "darji rohilla",
  "dhanak harijan",
  "dhanak khetak",
  "dhanak panghal",
  "dhanak verma",
  "dhanak",
  "dhimar kashyap",
  "dhobi dhobi",
  "dom harijan",
  "dom",
  "fakir shah",
  "gadaria pal",
  "gosai giri",
  "gosai",
  "goswami giri",
  "goswami",
  "goyal mahajan",
  "harijan ramdasi",
  "jaiswal",
  "jat badhai",
  "jat barai",
  "jat beniwal",
  "jat bhal",
  "jat bhambho",
  "jat bhullar",
  "jat birikhi",
  "jat chatrawal",
  "jat chaudhari",
  "jat chel",
  "jat chichar",
  "jat chopra",
  "jat dhaka",
  "jat dhankar",
  "jat fagadana",
  "jat godra",
  "jat jakahd",
  "jat jakhar",
  "jat jat",
  "jat jhiwar",
  "jat kaleri",
  "jat keol",
  "jat khaceri",
  "jat khayali",
  "jat kshliya",
  "jat kundu",
  "jat lohan",
  "jat malik",
  "jat mandal",
  "jat maun",
  "jat meel",
  "jat mod",
  "jat morwal",
  "jat nain",
  "jat panghal",
  "jat pannu",
  "jat prajapati",
  "jat puniya",
  "jat sahrawat",
  "jat samaran",
  "jat saran",
  "jat sharma",
  "jat shedkand",
  "jat sihag",
  "jat singla",
  "jat siwatch",
  "jat thalodi",
  "jat",
  "jat sikh",
  "jheemar kashyap",
  "jheemar",
  "jogi batti",
  "jogi gautam",
  "jogi jangam",
  "jogi nath",
  "jogi pada",
  "jogi rawal",
  "jogi",
  "julaha kabiram",
  "julaha kabirpath",
  "julaha koli",
  "kanhar gaur",
  "khati barai",
  "khati dhaman",
  "khati dhiman",
  "khati jagara",
  "khati jangada",
  "khati jangarh",
  "khati khati",
  "khati nath",
  "khati semar",
  "khati uttam",
  "khati",
  "khatri chappa",
  "khatri dhiman",
  "khatri khnna",
  "khatri khurana",
  "khatri uttam",
  "khatri",
  "kumhar harijan",
  "kumhar prajapati",
  "lakhera manihar",
  "lohar mistri",
  "lohar panchal",
  "lohar shakhala",
  "lohar tilak",
  "lohar vaishnav",
  "lohar vishwakarma",
  "lohar",
  "mahabrahman bhatt",
  "mahajan goyal",
  "mali saini",
  "manihar",
  "meo dahugal",
  "meo gorwal",
  "mirasi",
  "muslimlohar ali",
  "muslimlohar",
  "muslimteli derwal",
  "muslimteli khan",
  "muslimteli prajapati",
  "nai behadiyr",
  "nai diwakar",
  "nai gangotiya",
  "nai nai",
  "nai panghal",
  "nai pundir",
  "nai sainbakht",
  "nai semar",
  "nai thakur",
  "nai",
  "nayak kashyap",
  "nayak nayak",
  "nayak",
  "od",
  "pathan khan",
  "rabari dhiman",
  "rajput badgujak",
  "rajput chauhan",
  "rajput jhiwar",
  "rajput lodhi",
  "rajput rana",
  "rangrej jhiwar",
  "rewari rewari",
  "rewari",
  "saini mali",
  "saini sake",
  "saini",
  "sheikh abbashi",
  "sonar soni",
  "sonar verma",
  "sunar verma",
  "teli",
  "turha",
  "vaishya singla",
  "verma",
  "others",
  "ad-dharmi atar",
  "ad-dharmi bains",
  "ad-dharmi banga",
  "ad-dharmi chamar",
  "ad-dharmi chokhria",
  "ad-dharmi jassal",
  "ad-dharmi kaith",
  "ad-dharmi leel",
  "ad-dharmi mahi",
  "ad-dharmi mehto",
  "ad-dharmi powar",
  "ad-dharmi rai",
  "ad-dharmi sandhu",
  "ad-dharmi sidhu",
  "ad-dharmi thind",
  "ad-dharmi",
  "ahir yadav",
  "arora anand",
  "arora chawala",
  "arora kakar",
  "arora sood",
  "arora",
  "bairagi mahant",
  "balmiki chuhra",
  "balmiki ramdasi",
  "balmiki sobat",
  "balmiki sohata",
  "baniya goel",
  "baniya jaiswal",
  "bazigar jogi",
  "bharbhooja bhurji",
  "brahman atri",
  "brahman bharadwaj",
  "brahman chaubey",
  "brahman gogna",
  "brahman joshi",
  "brahman mahant",
  "brahman mudgil",
  "brahman rampal",
  "brahman saraswat",
  "brahman sharma",
  "brahman vaid",
  "braji baardua",
  "chamar jatav",
  "chamar ramdasi",
  "chamar ravidasi",
  "chhimbe dhami",
  "chhimbe jassal",
  "choudhary kashyap",
  "christian mashih",
  "christian",
  "dhobi ramdasi",
  "gadariya pal",
  "ghumair khan",
  "gonga",
  "gujjar",
  "gujjar(muslim) khan",
  "hadi hadi",
  "harijan atar",
  "harijan doma",
  "jat bhangu",
  "jat chahal",
  "jat her",
  "jat judge",
  "jat lalli",
  "jat nijjar",
  "jat saran",
  "jat",
  "jatsikh bassi",
  "jatsikh bhangu",
  "jatsikh bhinder",
  "jatsikh chahal",
  "jatsikh chimma",
  "jatsikh deol",
  "jatsikh ghuman",
  "jatsikh gill",
  "jatsikh grewal",
  "jatsikh gubanda",
  "jatsikh hans",
  "jatsikh her",
  "jatsikh jadge",
  "jatsikh judge",
  "jatsikh kaith",
  "jatsikh kang",
  "jatsikh khati",
  "jatsikh kokkar",
  "jatsikh lalli",
  "jatsikh lunj",
  "jatsikh maan",
  "jatsikh madan",
  "jatsikh mahant",
  "jatsikh mann",
  "jatsikh maur",
  "jatsikh mehra",
  "jatsikh mitha",
  "jatsikh nijjar",
  "jatsikh pakgi",
  "jatsikh pannu",
  "jatsikh rai",
  "jatsikh randhawa",
  "jatsikh samra",
  "jatsikh sandhu",
  "jatsikh saran",
  "jatsikh sharma",
  "jatsikh sidhu",
  "jatsikh sohal",
  "jatsikh tatla",
  "jatsikh thir",
  "jatsikh",
  "jhinwar lunj",
  "jhinwar mehra",
  "kabirpanthi julaha",
  "kahar durma",
  "kahtiyal mahasa",
  "kashyap jeer",
  "kehsavrajan chyor",
  "keshavrajput chyor",
  "kewat nishad",
  "khatri kapur",
  "khatri malhotra",
  "khatri",
  "kumhar prajapati",
  "kurmi patel",
  "kurmi verma",
  "kushwaha kushwaha",
  "lohar amra",
  "lohar bansal",
  "lohar dhele",
  "lohar dupad",
  "lohar kalri",
  "lohar khati",
  "lohar nadra",
  "lohar ramgarhia",
  "lohar suri",
  "lohar vishwakarma",
  "lohar",
  "maher maher",
  "marve",
  "mary",
  "mashim gill",
  "mashim jite",
  "massey",
  "mazhabi jite",
  "mazhabi maan",
  "mazhabi",
  "meena mothi",
  "mehra jeer",
  "mistri panesar",
  "nai bali",
  "nai dutta",
  "nai kalri",
  "nai kele",
  "nai phuman",
  "nai sidhu",
  "nai",
  "nath kokkar",
  "nath yogi",
  "nishad bind",
  "pasi paswan",
  "raisikh rai",
  "rajput baghariya",
  "rajput dadwal",
  "rajput jaiswal",
  "rajput kashyap",
  "rajput lodhi",
  "rajput mahajan",
  "rajput tayal",
  "rajput",
  "ramgrhia bansal",
  "saini pathan",
  "saini",
  "sansi bhangu",
  "sohata",
  "stat mary",
  "sunar bhagal",
  "sunar chino",
  "sunar gogna",
  "swarnkar",
  "teli gupta",
  "vaishya madan",
  "vaishya narang",
  "others",
  "brahman sharma",
  "chamar ajad",
  "chamar bhardwaj",
  "chamar bhatia",
  "chamar chauhan",
  "chamar julaha",
  "chamar kashyap",
  "chamar koli",
  "chamar lohar",
  "chamar majhare",
  "chamar mochi",
  "chamar",
  "jat",
  "rajput barwa",
  "rajput barwal",
  "rajput bhandari",
  "rajput bharmoria",
  "rajput bisht",
  "rajput dhalaria",
  "rajput khadhaka",
  "rajput kharwal",
  "rajput kumha",
  "rajput mandhotra",
  "rajput minya",
  "rajput nagwal",
  "rajput patiyal",
  "rajput sakalani",
  "rajput shahi",
  "rajput thakur",
  "rajput verma",
  "tarkhan",
  "others",
  "rajput others",
  "aarakh moothi",
  "aarakh yadav",
  "ahir yadav",
  "badhai chaurasia",
  "badhai nishad",
  "badhai panchal",
  "badhai panwari",
  "badhai sharma",
  "badhai vishwakarma",
  "bairagi",
  "balmiki balmiki",
  "bangali hela",
  "baniya goyal",
  "baniya gupta",
  "baniya jaiswal",
  "baniya kesarbani",
  "baniya sahu",
  "baniya tureha",
  "baniya varshney",
  "bayar barwar",
  "behna hanafi",
  "behna siddiqui",
  "bhangi balmiki",
  "bhangi upadhayay",
  "bhar rai",
  "bhar rajbhar",
  "bhar ray",
  "bhisti",
  "bhurji bharbhuja",
  "bhurji bhuj",
  "bhurji gupta",
  "bhurji mathur",
  "bhurji saxena",
  "brahman agnihotri",
  "brahman bairagi",
  "brahman bajpai",
  "brahman chaubey",
  "brahman dewedi",
  "brahman dixit",
  "brahman dubey",
  "brahman gaur",
  "brahman gautam",
  "brahman joshi",
  "brahman kaushik",
  "brahman mishra",
  "brahman ojha",
  "brahman pachori",
  "brahman pandey",
  "brahman pathak",
  "brahman rai",
  "brahman sharma",
  "brahman shukla",
  "brahman solanki",
  "brahman tiwari",
  "brahman tripathi",
  "brahman trivedi",
  "brahman tyagi",
  "brahman upadhayay",
  "brahmbhatt sharma",
  "brijbasinat nagar",
  "dafali hashmi",
  "darji idrishi",
  "dhanuk katheria",
  "dharkar vedvansi",
  "dhimar gautam",
  "dhimar kashyap",
  "dhimar tureha",
  "dhimar tursib",
  "dhobi diwakar",
  "dhobi gaur",
  "dhobi kanawa",
  "dhobi kannaujia",
  "dhobi nibariya",
  "dhobi pawar",
  "dhobi yadav",
  "dhuniya dhuniya",
  "dom nag",
  "dushad paswan",
  "fakir alvi",
  "fakir manihar",
  "fakir shah",
  "fakir sham",
  "fakir sheikh",
  "gadaria baghel",
  "gadaria pal",
  "gosai giri",
  "gujar bansal",
  "gujar dhama",
  "gujar drawat",
  "gujar kasana",
  "gujar nagar",
  "halwai gupta",
  "harijan chamar",
  "harijan dhama",
  "harijan jadav",
  "harijan jatav",
  "harijan kharwar",
  "harijan kori",
  "harijan mahor",
  "harijan paswan",
  "harijan rajak",
  "harijan rashi",
  "harijan rawat",
  "jat choudhary",
  "jat pawar",
  "jat payal",
  "jat sirohi",
  "jat tewatiya",
  "jogi tomar",
  "kachhi kushwaha",
  "kachhi maurya",
  "kahar dhuriya",
  "kahar gaur",
  "kahar gond",
  "kahar kahar",
  "kahar kashyap",
  "kahar kharwar",
  "kahar verma",
  "kalwar gupta",
  "kalwar jaiswal",
  "kalwar varsha",
  "kanhar gaur",
  "kanhar gava",
  "kanhar gond",
  "kanhar kharwar",
  "kayasth bhoumik",
  "kayasth mittal",
  "kayasth saxena",
  "kayasth srivastava",
  "kewat bind",
  "kewat choudhary",
  "kewat nishad",
  "khandu gupta",
  "kharwar benbansi",
  "kharwar benwasher",
  "khatik bamaniya",
  "khatik chik",
  "khatik sonar",
  "khatik sonkar",
  "kori kori",
  "kori kushwaha",
  "kori maurya",
  "kori pal",
  "kori verma",
  "kori",
  "kshatriya sengar",
  "kumhar gaur",
  "kumhar prajapati",
  "kurmi brahman",
  "kurmi kannaujia",
  "kurmi pandey",
  "kurmi patel",
  "kurmi verma",
  "lodh mahor",
  "lohar sharma",
  "lohar vishwakarma",
  "lohar yadav",
  "luniya chauhan",
  "mali saini",
  "manihar lakhera",
  "manihar qulandar",
  "manihar siddiqui",
  "mirasi abbal",
  "mominansari ansari",
  "muslim qureshi",
  "muslimdarji idrishi",
  "muslimdarji siddiqui",
  "muslimdhobi ali",
  "muslimdhobi ansari",
  "muslimdhobi baksh",
  "muslimdhobi dhama",
  "muslimdhobi dhuniya",
  "muslimdhobi dubey",
  "muslimdhobi kassar",
  "muslimdhobi khan",
  "muslimdhobi mansuri",
  "muslimdhobi sharma",
  "muslimdhobi sheikh",
  "muslimdhobi siddiqui",
  "muslimdhobi sulemani",
  "muslimgujar hashmi",
  "muslimhalwai ali",
  "muslimnai balwar",
  "muslimnai sulemani",
  "muslimnai turkata",
  "muslimrajput ansari",
  "muslimrajput fakir",
  "muslimrajput gaddi",
  "muslimrajput gond",
  "muslimrajput iraqi",
  "muslimrajput khan",
  "muslimrajput pathan",
  "muslimrajput qureshi",
  "muslimrajput saiyed",
  "muslimrajput sheikh",
  "muslimrajput siddiqui",
  "muslimrajput sulemani",
  "muslimsalmani sulemani",
  "muslimteli ali",
  "muslimteli malik",
  "muslimteli siddiqui",
  "nai bari",
  "nai brahai",
  "nai chandrawal",
  "nai dhama",
  "nai hardwariya",
  "nai nai",
  "nai rajauriya",
  "nai sain",
  "nai sharma",
  "pasi paswan",
  "pasi saroj",
  "pathan khan",
  "rajput baghel",
  "rajput balhariya",
  "rajput balkharya",
  "rajput bangar",
  "rajput beshen",
  "rajput bhadauriya",
  "rajput bhati",
  "rajput bhriguvanshi",
  "rajput bisen",
  "rajput brijwasi",
  "rajput chauhan",
  "rajput dikhit",
  "rajput gahlot",
  "rajput gaur",
  "rajput jarauliya",
  "rajput jatav",
  "rajput pandey",
  "rajput panwari",
  "rajput prajapati",
  "rajput qureshi",
  "rajput rajawat",
  "rajput rakwar",
  "rajput rana",
  "rajput rathore",
  "rajput sengar",
  "rajput sisodiya",
  "rajput solanki",
  "rajput somwansh",
  "rajput tomar",
  "rajput ujjaini",
  "ranghar khan",
  "saifi nor",
  "saifi siddiqui",
  "saiyed hussain",
  "saiyed kazi",
  "saiyed rizvi",
  "sheikh abbasi",
  "sheikh farooq",
  "sheikh mansuri",
  "sheikh siddiqui",
  "sonar soni",
  "teli gupta",
  "teli malik",
  "teli rathore",
  "teli sahu",
  "teli verma",
  "thakur dikhit",
  "yadav yadav",
  "brahman others",
  "rajput others",
  "others",
  "adiwasi handsa",
  "adiwasi hemram",
  "adiwasi marandi",
  "ahir rai",
  "ahir yadav",
  "baniya choudhary",
  "baniya gupta",
  "baniya kesri",
  "baniya sahu",
  "baniya shah",
  "baniya sharma",
  "barhai sharma",
  "brahamin sharma",
  "brahman dubey",
  "brahman giri",
  "brahman pandey",
  "brahman pathak",
  "brahman rai",
  "brahman tiwari",
  "brahman upadhyay",
  "chamar choudhary",
  "chamar kushwaha",
  "chamar paswan",
  "chamar",
  "dhobi rajak",
  "dhobi varetha",
  "dom",
  "dusadh paswan",
  "faqir miyan",
  "gund",
  "halwai sahu",
  "hari rai",
  "hari",
  "hussain",
  "julaha ansari",
  "kahar prasad",
  "kahar rawat",
  "kahar",
  "kayasth srivastav",
  "koeri kushwaha",
  "koeri mauriya",
  "koeri rai",
  "kulhaiya alam",
  "kulhaiya",
  "kumhar prjapati",
  "kumhar",
  "kumhar",
  "lohar prjapati",
  "lohar sharma",
  "mali bhagat",
  "mallah mahaldar",
  "musahar rishi",
  "musahar",
  "nai thakur",
  "pasi pasi",
  "pasi paswan",
  "pathan khan",
  "rajbhar rai",
  "rajput",
  "sahu choudhary",
  "santhali marandi",
  "santhali soren",
  "shaikh",
  "sheshwadi alam",
  "soren",
  "tanti",
  "tatwa choudhary",
  "tatwa das",
  "tatwa",
  "teli kushwaha",
  "teli sahu",
  "teli shah",
  "vishwakarma sharma",
  "others",
  "aguri aditya",
  "aguri angror",
  "aguri balgori",
  "aguri phulakatamali",
  "bagdi daratia",
  "bagdi machua",
  "bagdi noda",
  "bagdi phulakatamali",
  "bagdi sundi",
  "bairagi bahari",
  "bairagi bairagi",
  "banik desashram",
  "banik gandhabanik",
  "bauri chasa",
  "bauri chasha",
  "bauri dulia",
  "bauri mallabhumia",
  "bayen bajunia",
  "brahman bairagi",
  "brahman barendra",
  "brahman kaibarta",
  "brahman rarhi",
  "brahman vaidik",
  "chamar mochi",
  "chutor chutor",
  "dhoba bangalidhoba",
  "dom akure",
  "dom jhalo",
  "dom mochi",
  "dulia chasa",
  "dulia chasha",
  "dulia sundi",
  "gandharahik ashram",
  "gandharahik desashram",
  "gandharahik sankha",
  "gandharahik sankhaashram",
  "garai daratia",
  "garai teli",
  "gowala barendra",
  "gowala gop",
  "gowala gope",
  "hari abari",
  "hari sau",
  "hari sundi",
  "hembram bital",
  "jele bhunja",
  "jele kumar",
  "jele kusmete",
  "jele machua",
  "jele mashon",
  "kaibarta jala",
  "kaibarta kaibarta",
  "kalu daratia",
  "kalu rarhi",
  "kalu teli",
  "kamar belashi",
  "kamlu teli",
  "karmakar belashi",
  "karmakar",
  "kayastha aditya",
  "kayastha barendra",
  "kayastha bhunja",
  "kayastha rarhi",
  "koibartr halik",
  "kol kol",
  "kolhu kachuarolma",
  "kora hatea",
  "koronga dwada",
  "koronga jele",
  "kotal bhunia",
  "kotal kantch",
  "kotal uttararin",
  "kumar chasha",
  "kumar kumar",
  "kumar rarhi",
  "kurmi chandal",
  "kurmi chapwar",
  "mahaishya bagla",
  "mahaishya bagula",
  "mahaishya benatia",
  "mahaishya chasikotal",
  "mahaishya chukulia",
  "mahaishya eenatia",
  "mahaishya kotal",
  "mahaishya manduchasa",
  "mahaishya munduchasa",
  "mahali bansphoremaheli",
  "mahali bital",
  "majhi bhatwar",
  "majhi kusmete",
  "malakar phulakatamali",
  "mali phulakatamali",
  "mali sukulkara",
  "mallah mallah",
  "malo malo",
  "mandi handi",
  "mayra kotal",
  "mayra modak",
  "mete daratia",
  "modak moira",
  "moira kotal",
  "moira purabiya",
  "mudi boar",
  "muellu teli",
  "munda kolmunda",
  "muniya bhojpuriya",
  "murmu bital",
  "murmu handi",
  "murmu",
  "murmu",
  "muslim",
  "namasudra namasudra",
  "napit barendra",
  "napit paramanik",
  "napit paschimrarhi",
  "nayak sahar",
  "nomosudra namasudra",
  "nuniya bhojpuriya",
  "paliya paliya",
  "paramanik napit",
  "patni teli",
  "rabidas janpur",
  "rabidas jonpuri",
  "rabidas machua",
  "rabidas mochi",
  "rajbanshi rajbanshi",
  "rajwar ahir",
  "sadgope bhunja",
  "sadgope chasa",
  "sadgope chasha",
  "sadgope gop",
  "sadgope purbakuliya",
  "santhal abari",
  "santhal bital",
  "santhal boar",
  "santhal desaisanthal",
  "santhal deswalisanthal",
  "santhal handi",
  "santhal muro",
  "sarbjar dakshinrarhi",
  "sardar chapwar",
  "sarnakar dakshinrarhi",
  "sunri rarhi",
  "sunri sundi",
  "suphra lasira",
  "suri sundi",
  "tanti hasantanti",
  "tanti rarhi",
  "tanti sikhiria",
  "tantubai baendra",
  "tantubai bairagi",
  "tantubai barendra",
  "tantubai rarhi",
  "tantubai tanti",
  "tili bhunja",
  "tili gachhuakalu",
  "tili",
  "tomar rarhi",
  "tuntubai rarhi",
  "tuntubai tanti",
  "ugrakshtriya aditya",
  "ugrakshtriya balgori",
  "ugrakshtriya napit",
  "ugrakshtriya",
  "varmakar belashi",
  "others",
  "ahir sahu",
  "ahir shah",
  "ahir turi",
  "ahir yadav",
  "ahir",
  "ashur",
  "badhai mistry",
  "baniya barnawal",
  "baniya mistry",
  "baniya modi",
  "baniya sahu",
  "baniya yadav",
  "baniya",
  "barhai mistry",
  "bhumihar mishra",
  "bhumihar pandey",
  "bhumihar",
  "brahman awashthi",
  "brahman bharati",
  "brahman dubey",
  "brahman mishra",
  "brahman pandey",
  "brahman tiwari",
  "brahman upadhayay",
  "chamar bhuian",
  "chamar das",
  "chamar julaha",
  "chamar mahali",
  "chamar ravidas",
  "chamar turi",
  "chamar",
  "dhobi rajak",
  "dusad paswan",
  "edris khalifa",
  "fakir shah",
  "gandrap rana",
  "ghatwal rai",
  "ghatwal ray",
  "halwai",
  "kahar julaha",
  "kahar prajapati",
  "kahar rawni",
  "kahar",
  "kandu shah",
  "kayastha sinha",
  "kayastha verma",
  "kayastha",
  "kharwar",
  "kumhar pal",
  "kumhar prajapati",
  "kurmi raut",
  "lohar sahu",
  "lohar vishwakarma",
  "lohar",
  "mali malakar",
  "mali",
  "mandal raut",
  "mehtar hadi",
  "mehtar jadi",
  "mominansari julaha",
  "mominansari miyan",
  "mominansari sahu",
  "mran julaha",
  "musahar bhuian",
  "musahar",
  "muslimdhobi idrishi",
  "muslimdhobi miyan",
  "muslimdhobi thakur",
  "nai thakur",
  "oraon birjiya",
  "oraon",
  "pasi choudhary",
  "pasi mistry",
  "pasi",
  "pathan khan",
  "rajput choudhary",
  "rajput raut",
  "rajput sahu",
  "rajput sonar",
  "rajput",
  "rajvanshi julaha",
  "rajvanshi",
  "rajwar rajbansi",
  "rawani julaha",
  "rawani",
  "santhal baski",
  "santhal basra",
  "santhal bishra",
  "santhal dehri",
  "santhal hansda",
  "santhal hemram",
  "santhal kishu",
  "santhal kisku",
  "santhal marandi",
  "santhal murmu",
  "santhal soren",
  "santhal tudu",
  "sheikh",
  "siddiqui",
  "sonar sonar",
  "sonar soni",
  "sonar swarnkar",
  "sudhi sahu",
  "sudhi shah",
  "teli idrishi",
  "teli julaha",
  "teli modi",
  "teli sahu",
  "teli shah",
  "teli turi",
  "teli yadav",
  "teli",
  "thathera",
  "turi dayal",
  "turi turi",
  "turi",
  "others",
  "arh adiwasi bhena",
  "arh adiwasi bhend",
  "arh adiwasi bhenil",
  "arh adiwasi binjhwar",
  "arh adiwasi dhanwar",
  "arh adiwasi dhimar",
  "arh adiwasi goari",
  "arh adiwasi gond",
  "arh adiwasi kanwar",
  "arh adiwasi nagarchi",
  "arh adiwasi sarthi",
  "arh adiwasi sidar",
  "arh ahir nagarchi",
  "arh ahir rao",
  "arh ahir rawat",
  "arh ahir sahu",
  "arh ahir teli",
  "arh ahir yadav",
  "arh bairagi vaishno",
  "arh banjara",
  "arh bhaina ram",
  "arh biar vaishno",
  "arh brahman bairagi",
  "arh brahman bajpayee",
  "arh brahman banjara",
  "arh brahman devedi",
  "arh brahman dixit",
  "arh brahman dubey",
  "arh brahman gandharu",
  "arh brahman goswami",
  "arh brahman joshi",
  "arh brahman mishra",
  "arh brahman pandey",
  "arh brahman sharma",
  "arh brahman shukla",
  "arh brahman tiwari",
  "arh brahman vasudev",
  "arh brahman",
  "arh brhaman sharma",
  "arh chamar anant",
  "arh chamar banjara",
  "arh chamar bhandarkar",
  "arh chamar dayal",
  "arh chamar dhare",
  "arh chamar dinkar",
  "arh chamar gareg",
  "arh chamar kariyare",
  "arh chamar khote",
  "arh chamar manik",
  "arh chamar meher",
  "arh chamar nirmal",
  "arh chamar rai",
  "arh chamar raidas",
  "arh chamar ratrea",
  "arh chamar rohidas",
  "arh chamar sahu",
  "arh chamar satnami",
  "arh chamar suryavanshi",
  "arh chamar suryawansi",
  "arh das mahant",
  "arh das manikpur",
  "arh das panik",
  "arh dhanwar",
  "arh dhimar bhatiyar",
  "arh dhimar machhandar",
  "arh dhimar tarail",
  "arh dhimar yadav",
  "arh dhobi karash",
  "arh dhobi nirmal",
  "arh dhobi nirmalkar",
  "arh dhobi varetha",
  "arh dhurwa dhruv",
  "arh dhurwa ram",
  "arh gadaria pal",
  "arh gadariya pal",
  "arh gandha dhruv",
  "arh gond bhakam",
  "arh gond chauhan",
  "arh gond dhruv",
  "arh gond kanwar",
  "arh gond markam",
  "arh gond nagarchi",
  "arh gond netam",
  "arh gond pardhi",
  "arh gond sidar",
  "arh gond tarail",
  "arh gond",
  "arh gori khan",
  "arh goswami",
  "arh gour gour",
  "arh gour sidar",
  "arh gour",
  "arh harijan meher",
  "arh kallar dadsena",
  "arh kallar darsena",
  "arh kallar parsaj",
  "arh kallar parsh",
  "arh kallar sinha",
  "arh kalwar sinha",
  "arh kanwar dewan",
  "arh kanwar sidar",
  "arh karara markam",
  "arh kawar dewan",
  "arh kawar kawar",
  "arh kawar sidar",
  "arh kewat bagher",
  "arh kewat nagarchi",
  "arh kewat niishad",
  "arh kewat nisad",
  "arh kewat nishad",
  "arh kewat nishadraj",
  "arh kewat patel",
  "arh koshtha koshtha",
  "arh kumhar prajapati",
  "arh kurmi adil",
  "arh kurmi baghel",
  "arh kurmi dayal",
  "arh kurmi gabel",
  "arh kurmi patel",
  "arh kurmi ppatel",
  "arh kurmi sahu",
  "arh kurmi shing",
  "arh kurmi tikariya",
  "arh kurmi verma",
  "arh lohar sher",
  "arh lohar vishkarma",
  "arh lohar vishwakarma",
  "arh lohar viswakarma",
  "arh mangia nagarchi",
  "arh marar patel",
  "arh nagarchi satnami",
  "arh nagarchi sonwali",
  "arh nagarchi",
  "arh nai sen",
  "arh nai sri",
  "arh nai sriwas",
  "arh nayak nayak",
  "arh pardhi dhruv",
  "arh patkar",
  "arh patwa patka",
  "arh patwa patkar",
  "arh patwa poddhar",
  "arh rajput chauhan",
  "arh rajput",
  "arh sabiriya",
  "arh sindhi jagmalani",
  "arh sonar sahu",
  "arh sonar soni",
  "arh sonar sony",
  "arh teli hirondhi",
  "arh teli prasad",
  "arh teli sahu",
  "arh teli shahu",
  "arh teli sonkanthari",
  "arh others",
  "alial gopalpuria",
  "badhei choursia",
  "badhei kharada",
  "badhei maghiya",
  "baisnab baisnab",
  "baistamba upadhyay",
  "bangali bengali",
  "bangali chasa",
  "baniya ayodhabasi",
  "baniya oriyabaniya",
  "baniya oriyamunda",
  "baniya sunari",
  "barik satagharia",
  "bauri bauri",
  "bauri pathuriya",
  "benayat chakulia",
  "benayat gouda",
  "benayat munda",
  "benayat satagharia",
  "benayat sukulia",
  "benayat",
  "bhandari chasa",
  "bhandari napita",
  "bhandari radhi",
  "bhandari satagharia",
  "bhandari",
  "bhatera yogi",
  "bhoi sahara",
  "bhumija oriyamunda",
  "bhumija radhi",
  "bhuyan khandayat",
  "brahman baisnab",
  "brahman balabhadra",
  "brahman barendra",
  "brahman bhattamishra",
  "brahman chasa",
  "brahman dakhinoriya",
  "brahman danua",
  "brahman devila",
  "brahman jadurbade",
  "brahman samanta",
  "brahman sasani",
  "brahman upadhaya",
  "brahman upadhyay",
  "brahman",
  "chamar chamar",
  "chamar magahia",
  "chasa munda",
  "chasa parida",
  "danbasi chasa",
  "dhoba dhoba",
  "dhoba goura",
  "dhoba maghiya",
  "dhoba oriya",
  "dhoba oriyadhoba",
  "duma mithar",
  "duma oriyamunda",
  "ganda rajganda",
  "gaud dumala",
  "gaud goura",
  "gaud rajgond",
  "gaud rajmunda",
  "ghantora nair",
  "ghasi siuli",
  "ghukha radhi",
  "ghusuria radhi",
  "gokha kandara",
  "gokha radhi",
  "gond rajgond",
  "gopal abhi",
  "gopal dumala",
  "gopal dumali",
  "gopal gopal",
  "gopal gopalpuria",
  "gopal gour",
  "gopal goura",
  "gopal magadha",
  "gopal mathurabai",
  "gopal munda",
  "gopal",
  "goti goti",
  "gudia bhojpuria",
  "gudia goura",
  "gudia kanaujia",
  "gudia madesia",
  "gudia maghayat",
  "gudia maghiya",
  "gudia munda",
  "gudia puribia",
  "hadi hadi",
  "hadi mahar",
  "hadi mehetar",
  "hadi mithar",
  "jogi jogi",
  "jyotska matimansa",
  "kachara kachara",
  "kaibart chasa",
  "kaibart gokha",
  "kaibart kandara",
  "kaibart munda",
  "kaibart radhi",
  "kalanji munda",
  "kamar khatya",
  "kandara kandara",
  "kandara kandara",
  "kapudia kapudia",
  "karan betra",
  "karan maghiya",
  "karan mahanaik",
  "karan naulikaran",
  "karan",
  "kela radhi",
  "kela sabakhia",
  "kela",
  "kendara kandara",
  "keuta radhi",
  "khadala jhatia",
  "khadia khadia",
  "khandayat chasa",
  "khandayat kandara",
  "khandayat khandayat",
  "khandayat maghiya",
  "khandayat mahanaik",
  "khandayat munda",
  "khandayat odukhandayat",
  "khandayat oriyamunda",
  "khandayat srestakhandayat",
  "khandayat",
  "khejari kol",
  "khetriya mahanaik",
  "khetriya orhkhandayat",
  "khodala betra",
  "kolar munda",
  "kolha kolha",
  "kolha munda",
  "kulta chasa",
  "kulta kol",
  "kulta munda",
  "kulta odachasa",
  "kumbhar jaganathi",
  "kumbhar khatya",
  "kumbhar matiakumbhar",
  "kumbhar oriyakumbhar",
  "kumuti haldia",
  "kumuti kumuti",
  "lohar oriyakamar",
  "mahar mahar",
  "maharana maghiya",
  "mali dokanimali",
  "mali kol",
  "mali phulkata",
  "mochi karaya",
  "mochi mihtar",
  "mochi mithar",
  "mochi oriyamunda",
  "munda kol",
  "munda kola",
  "munda oraonmunda",
  "munda oriyamunda",
  "muslim",
  "nihar chudakutakeuta",
  "nihar radhi",
  "oram oraonmunda",
  "oram oriyamunda",
  "pana betra",
  "pana oriyapana",
  "patara patara",
  "sahara kol",
  "sahara sabar",
  "sahara savar",
  "sihamuslim",
  "sundhi sundhi",
  "tanti chasa",
  "tanti galatanti",
  "tanti hansi",
  "tanti matibansa",
  "teli abhi",
  "teli gouda",
  "teli haldia",
  "teli hansi",
  "teli kalu",
  "teli tulatia",
  "thatari thatari",
  "vaisya chasa",
  "yogi yogi",
  "abdul",
  "achari",
  "adiandra",
  "ailceej",
  "archakulu",
  "arya kashtriya",
  "arya vysya",
  "asadulu",
  "baaraju",
  "bajakas",
  "balija bandari",
  "balija cettibalija",
  "balija cheemala",
  "balija chinnkapu",
  "balija dudekula",
  "balija gazula",
  "balija kudari",
  "balija naika",
  "balija palagiri",
  "balija periki",
  "balija pokanti",
  "balija setti",
  "balija settibalija",
  "balija settivari",
  "balija telaga",
  "balija",
  "barber",
  "bestha cheemala",
  "bestha dasai",
  "bestha jalari",
  "bestha jalaru",
  "bestha kudari",
  "bestha mateshp",
  "bestha naika",
  "bestha pokanti",
  "bestha sayed",
  "bestha sella",
  "bestha valmiki",
  "bestha yadav",
  "bestha",
  "bondil",
  "bothula",
  "boya anke",
  "boya cheemala",
  "boya deragulla",
  "boya dommara",
  "boya dudekula",
  "boya jalleni",
  "boya jamapala",
  "boya jhamala",
  "boya jutur",
  "boya kandi",
  "boya kudari",
  "boya nagiri",
  "boya naidu",
  "boya naika",
  "boya peddaboya",
  "boya pinjari",
  "boya pokanti",
  "boya sayed",
  "boya vaddi",
  "boya valmiki",
  "boya yadav",
  "boya yerragolla",
  "boya",
  "brahman sidhanthi",
  "brahman vaidhika",
  "brahman",
  "budabukkala",
  "bukava",
  "camsula",
  "chakala bilishpalla",
  "chakala dhobi",
  "chakala dudekula",
  "chakala jalnul",
  "chakala mallepulu",
  "chakala",
  "chakali dudekula",
  "chakali pokanti",
  "chakali",
  "chenchu",
  "christian madiga",
  "christian",
  "devara",
  "dhobi chakala",
  "dhobi dudekula",
  "dhobi gunje",
  "dhobi naika",
  "dhobi pokanti",
  "dhobi shaik",
  "dhobi",
  "dommara dommara",
  "dommara dudekula",
  "dommara",
  "ediga chakala",
  "ekaradorabiddalu",
  "ekili palayakarlu",
  "ekili",
  "elakula",
  "elems",
  "fishers",
  "gandla sayed",
  "gandla",
  "gangtredhu",
  "jangam",
  "kadulu",
  "kalali",
  "kalasali",
  "kaligullu",
  "kama",
  "kamasala gunje",
  "kamasala mettu",
  "kamasala",
  "kamma choudhary",
  "kamma",
  "kammara gundaiah",
  "kammara mettukamsali",
  "kantlli",
  "kapu adupol",
  "kapu cheemala",
  "kapu chendiya",
  "kapu chinnkapu",
  "kapu desai",
  "kapu dudekula",
  "kapu jalaru",
  "kapu jutar",
  "kapu jutur",
  "kapu karnam",
  "kapu krishnam",
  "kapu madiga",
  "kapu munnuru",
  "kapu naika",
  "kapu padupollu",
  "kapu pagani",
  "kapu pakanti",
  "kapu palagiri",
  "kapu palli",
  "kapu pasnur",
  "kapu pedakapu",
  "kapu pokanti",
  "kapu sajjana",
  "kapu shaik",
  "kapu sunku",
  "kapu talapalli",
  "kapu telaga",
  "kapu turpukapu",
  "kapu",
  "kapu",
  "kapuvelama kapu",
  "kapuvelama maipu",
  "kapuvelama naga",
  "kapuvelama naidu",
  "kapuvelama padamasali",
  "kapuvelama sahukar",
  "kapuvelama sanka",
  "kapuvelama talaka",
  "kapuvelama tulasi",
  "kapuvelama tusasi",
  "kapuvelama",
  "karnam",
  "kavunis",
  "kayunllu",
  "khan pathan",
  "kolli",
  "komati",
  "kommari dudekula",
  "koppalavelama",
  "kopplavelama",
  "kouda",
  "koya",
  "kummara chendiya",
  "kummara gundaiah",
  "kummara kummara",
  "kummara",
  "kuppalavelama",
  "kuraba chendiya",
  "kuraba dupati",
  "kuraba jella",
  "kuraba mallepulu",
  "kuraba",
  "madarlu",
  "madiga madiga",
  "madiga rachama",
  "madiga sungulu",
  "madiga",
  "madivili",
  "mala dasari",
  "mala mangam",
  "mala saki",
  "mala telaga",
  "mala vangam",
  "mala",
  "mandiga",
  "mandula",
  "mangala konda",
  "mangala reddy",
  "mangala",
  "mangali",
  "marwadi",
  "maryali",
  "miniramanu",
  "modugu",
  "mondi",
  "muslim bohra",
  "muslim cheemala",
  "muslim dudekula",
  "muslim golla",
  "muslim gunje",
  "muslim jalari",
  "muslim jalleni",
  "muslim jhamala",
  "muslim kudari",
  "muslim mateshp",
  "muslim naika",
  "muslim pathan",
  "muslim sayed",
  "muslim shaik",
  "muslim",
  "muthrasi achhntala",
  "muthrasi kanaga",
  "muthrasi magurupuvati",
  "muthrasi mogili",
  "muthrasi muthrasi",
  "muthrasi padgawadu",
  "muthrasi pala",
  "muthrasi palfagun",
  "muthrasi",
  "nadar",
  "nagvamsham",
  "naidu yagili",
  "naidu",
  "nainera",
  "nayaka",
  "naybrahmanulu",
  "nese cheemala",
  "nese naika",
  "nese palla",
  "nese sayed",
  "nese",
  "odde boya",
  "odde",
  "padmasali",
  "pagani golla",
  "palaeikri shaik",
  "palaeikri",
  "palikapu shaik",
  "palikapu vaddi",
  "palikapu",
  "palle agni",
  "palle",
  "petti",
  "pingari golla",
  "pingari yadav",
  "pujari pandit",
  "rabbari",
  "rajaka kanaga",
  "rajaka",
  "rajakulu",
  "rajasthani",
  "rajulu",
  "ralliya",
  "reddy kondareddy",
  "reddy velamakapu",
  "reddy velamareddy",
  "reddy",
  "relli settibalija",
  "relli",
  "sakala anke",
  "sakala vaddi",
  "sakala yalama",
  "sakala",
  "sakli",
  "sali",
  "salilu",
  "salivahana",
  "sarabandu",
  "satyam",
  "sayed",
  "segu yalama",
  "setti devanga",
  "setti vyasya",
  "shadi",
  "sheetbarjen",
  "sheikh anke",
  "sheikh bohra",
  "sheikh boya",
  "sheikh choudhary",
  "sheikh dhobi",
  "sheikh dudekula",
  "sheikh golla",
  "sheikh neeku",
  "sheikh sayed",
  "sheikh settibalija",
  "sheikh sheikhpathan",
  "sheikh sudkula",
  "sheikh suryabalija",
  "sheikh telaga",
  "sheikh yalama",
  "sheikh",
  "sugali banjara",
  "sugali boipari",
  "sugali devasat",
  "sugali lambani",
  "sugali lambari",
  "sugali meguat",
  "sugali",
  "talari anke",
  "telagamamdelu",
  "telakula",
  "teli sahukar",
  "teli",
  "teluku",
  "tentkalu",
  "togata",
  "uppara",
  "vaddi cheemala",
  "vaddi dudekula",
  "vaddi gunje",
  "vaddi kudari",
  "vaddi manjari",
  "vaddi naika",
  "vaddi palla",
  "vaddi pathan",
  "vaddi sampangi",
  "vaddi sayed",
  "vaddi shaik",
  "vaddi valmiki",
  "vaddi",
  "vadi palappu",
  "vangam anke",
  "vedava",
  "velama brahman",
  "velama kapu",
  "velama nagala",
  "velama",
  "vikanasa",
  "visali",
  "visalu",
  "vishnu",
  "viswabrahaman brahman",
  "viswabrahaman",
  "vysya adimulam",
  "vysya aryavysa",
  "vysya brahman",
  "vysya cheemala",
  "vysya dudekula",
  "vysya kakunati",
  "vysya karumani",
  "vysya komati",
  "vysya krishnam",
  "vysya naika",
  "vysya pokanti",
  "vysya sayed",
  "vysya sunku",
  "vysya ysya",
  "vysya",
  "vyyulu",
  "yadav alagolla",
  "yadav anke",
  "yadav golla",
  "yadav gouda",
  "yadav jalaru",
  "yadav jhamala",
  "yadav jutur",
  "yadav konar",
  "yadav kudari",
  "yadav namala",
  "yadav pagani",
  "yadav palagiri",
  "yadav pokanti",
  "yadav poojagolla",
  "yadav settivari",
  "yadav shaik",
  "yadav talapalli",
  "yadav telaga",
  "yadav valmiki",
  "yadav yadav",
  "yadav yerragolla",
  "yadav",
  "yalama",
  "yalavala kapu",
  "yanadi yelleu",
  "yanadi",
  "yeava",
  "yellu",
  "yerkula",
  "yerukala desai",
  "yerukala",
  "yerukula",
  "ablakaror",
  "achagar osamani",
  "achary",
  "adidravida .pallar",
  "adidravida barbar",
  "adidravida harijan",
  "adidravida kuavar",
  "adidravida kuravar",
  "adidravida maruthavari",
  "adidravida muruthuar",
  "adidravida nadar",
  "adidravida padaiyachi",
  "adidravida pallar",
  "adidravida panditar",
  "adidravida parayar",
  "adidravida pattaraju",
  "adidravida pollar",
  "adidravida poraya",
  "adidravida sakkeliar",
  "adidravida thachar",
  "adidravida thombar",
  "adidravida valayar",
  "adidravida vannan",
  "adidravida",
  "agamudiyar pillai",
  "agamudiyar sayup",
  "agamudiyar",
  "ambalaar moopanaar",
  "ambalaar",
  "ambalam",
  "ammalam",
  "archagar",
  "arundudhi",
  "arunthathi padaiyachi",
  "arunthathi sakkeliar",
  "arunthathi",
  "asari goldsmith",
  "asari kamalar",
  "asari kounda",
  "asari padaiyachi",
  "asari pathar",
  "asari thachaasari",
  "asari",
  "athidravida asari",
  "athidravida palar",
  "athidravida pallar",
  "athidravida parayar",
  "athidravida pollar",
  "athidravida sakkeliar",
  "athidravida samabavar",
  "athidravida valayar",
  "athidravida",
  "ayyar tenkalai",
  "ayyar",
  "bandaram andi",
  "banniyar padaiyachi",
  "brahman aadisaiver",
  "brahman ayan",
  "brahman ayyangar",
  "brahman iyyar",
  "brahman",
  "chettiyar bathmasaliyar",
  "chettiyar boyar",
  "chettiyar choli",
  "chettiyar gulalar",
  "chettiyar kavara",
  "chettiyar kulalan",
  "chettiyar kullalar",
  "chettiyar kuyavar",
  "chettiyar manbanachettiyar",
  "chettiyar nayakkar",
  "chettiyar nesauchittiyar",
  "chettiyar padaiyachi",
  "chettiyar sanathaliar",
  "chettiyar sanothalaiar",
  "chettiyar soleya",
  "chettiyar soliar",
  "chettiyar soliarpallar",
  "chettiyar soliya",
  "chettiyar soneya",
  "chettiyar telunguchettiyar",
  "chettiyar thelugu",
  "chettiyar tholuva",
  "chettiyar vaaniga",
  "chettiyar valayar",
  "chettiyar vaniba",
  "chettiyar vaniyar",
  "chettiyar vellachettiyar",
  "chettiyar",
  "chetty coirchetty",
  "chetty satha",
  "chetty soliar",
  "chetty soliya",
  "chetty tholuva",
  "chetty",
  "christian",
  "curavan",
  "dhobi dhobi",
  "dhobi vannan",
  "dhobi",
  "dube tholuva",
  "dube",
  "duluvar vellalar",
  "gounder dhobi",
  "gounder ganguvellar",
  "gounder gonar",
  "gounder hellar",
  "gounder keailiya",
  "gounder kongu",
  "gounder krumbar",
  "gounder kurambar",
  "gounder kuramo",
  "gounder kurma",
  "gounder kurumbar",
  "gounder lattuan",
  "gounder man",
  "gounder nadar",
  "gounder sarvai",
  "gounder valayar",
  "gounder vellalar",
  "gounder vellalgoundar",
  "gounder vettuubn",
  "gounder",
  "iyyar dasingar",
  "iyyar gurkal",
  "iyyar kurukal",
  "iyyar pragasaranam",
  "iyyar",
  "kammalar asari",
  "kammalar padaiyachi",
  "kammalar pathar",
  "kammalar thachar",
  "karunegar",
  "kauvnder gongu",
  "kauvnder kallar",
  "kauvnder kalvala",
  "kauvnder kangu",
  "kauvnder kongu",
  "kauvnder",
  "konar vellalar",
  "konar yadav",
  "konar yadavar",
  "konar",
  "krishnanvagai asari",
  "krishnanvagai krishnanvagai",
  "krishnanvagai nadar",
  "krishnanvagai pallar",
  "krishnanvagai r.c.nadar",
  "krishnanvagai vagai",
  "krishnanvagai",
  "kulavar",
  "kurumbar kallar",
  "kurumbar peramalaikallar",
  "kurumbar",
  "kusavar man",
  "kusavar",
  "labbari",
  "lappa",
  "lappee",
  "lebbai",
  "lillai soliar",
  "maidukavara tholuva",
  "manyakaran maniakaran",
  "maruthuvar navithan",
  "maruthuvar sembadavar",
  "maruthuvar",
  "meenavar fernando",
  "meenavar musali",
  "meenavar sembadavar",
  "moopnar ambalahar",
  "moopnar vadayar",
  "moopnar valayar",
  "moopnar",
  "mothaliar asari",
  "mothaliar benguthen",
  "mothaliar kaigonar",
  "mothaliar karkala",
  "mothaliar keralamuthali",
  "mothaliar keralamuythaliyar",
  "mothaliar naidu",
  "mothaliar sangunthan",
  "mothaliar sengunthamudaliyar",
  "mothaliar",
  "mubbanar kallar",
  "mubbanar",
  "mudaliyar kaicooly",
  "mudaliyar sangunthan",
  "mudaliyar sengundar",
  "mudaliyar soliya",
  "mudaliyar thondi",
  "mudaliyar thondimandala",
  "mudaliyar",
  "muppan valayar",
  "muppar kallar",
  "muppar valayar",
  "muppar",
  "muslim labbai",
  "muslim leppai",
  "muslim rabbai",
  "muslim ravuthur",
  "muslim syed",
  "muslim",
  "muthiriar ambalam",
  "muthiriar sangunthan",
  "muthiriar",
  "nadar asari",
  "nadar chanar",
  "nadar gramani",
  "nadar hindu",
  "nadar hindunadar",
  "nadar kamraj",
  "nadar lattuan",
  "nadar marama",
  "nadar marameri",
  "nadar maramerinadar",
  "nadar maramerinaikar",
  "nadar maramynar",
  "nadar maravar",
  "nadar nadar",
  "nadar nayakkar",
  "nadar pallar",
  "nadar pananarayanarayer",
  "nadar r.c.nadar",
  "nadar saanan",
  "nadar sacuar",
  "nadar sanar",
  "nadar senar",
  "nadar sundar",
  "nadar tennai",
  "nadar vagai",
  "nadar",
  "naidu cheruai",
  "naidu chettynaidu",
  "naidu gavar",
  "naidu jangam",
  "naidu kamalar",
  "naidu kanvara",
  "naidu kavara",
  "naidu kevara",
  "naidu mraamars",
  "naidu muthiriyar",
  "naidu palginaidu",
  "naidu pallar",
  "naidu pattaraju",
  "naidu ravara",
  "naidu sanar",
  "naidu sanarnaidu",
  "naidu vadugan",
  "naidu valayar",
  "naidu",
  "naikar kadu",
  "naikar kamalar",
  "naikar kambalathu",
  "naikar kavara",
  "naikar krishnanvagai",
  "naikar kuravar",
  "naikar marameri",
  "naikar maramerinaikar",
  "naikar naidu",
  "naikar nayakkar",
  "naikar padaiyachi",
  "naikar pallar",
  "naikar sanar",
  "naikar vagai",
  "nair nadar",
  "nair pillai",
  "nair r.c.nadar",
  "nair",
  "navithar barbar",
  "navithar",
  "nuber kuramo",
  "pandaram andi",
  "pandaram",
  "pandithar barbar",
  "pandithar maruthavari",
  "pandithar",
  "parayan barbar",
  "parayan",
  "patthar asari",
  "pillai asari",
  "pillai ectar",
  "pillai kagatha",
  "pillai karkala",
  "pillai kodika",
  "pillai kuramo",
  "pillai nair",
  "pillai panikkar",
  "pillai saiva",
  "pillai soleyavellalor",
  "pillai soliar",
  "pillai soliya",
  "pillai theva",
  "pillai tholuva",
  "pillai tholuvavellalar",
  "pillai thullam",
  "pillai veeragul",
  "pillai veerakodai",
  "pillai veeravellar",
  "pillai vellalar",
  "pillai veragudivellalar",
  "pillai",
  "pillamer ilathu",
  "pillamer",
  "rajaliar",
  "rammalar thachar",
  "raouther",
  "rawhar",
  "reddiyar",
  "reddy",
  "seruai agamudaiyar",
  "seruai",
  "setiyar vaniba",
  "shawrastra",
  "soleya vellalar",
  "soleya",
  "thaysigar kurukal",
  "thevar agamudaiyar",
  "thevar alagamudai",
  "thevar ambalam",
  "thevar gurkal",
  "thevar kallar",
  "thevar kamalar",
  "thevar kuyavar",
  "thevar maniakaran",
  "thevar maravar",
  "thevar muthiriyar",
  "thevar nadar",
  "thevar nattukakallar",
  "thevar pallar",
  "thevar parama",
  "thevar peramalaikallar",
  "thevar sarvai",
  "thevar soliar",
  "thevar tholuva",
  "thevar vandayaar",
  "thevar",
  "vadukanaikar",
  "valayar",
  "vallalar goundar",
  "vallalar guruvel",
  "vallalar pillai",
  "vanan",
  "vanar washerman",
  "vaniyar chadiyar",
  "vaniyar dhobi",
  "vaniyar dobi",
  "vaniyar goundar",
  "vaniyar kallar",
  "vaniyar karkathavellalar",
  "vaniyar kounda",
  "vaniyar mooppar",
  "vaniyar naikar",
  "vaniyar nathamar",
  "vaniyar nathana udaiyar",
  "vaniyar nayakkar",
  "vaniyar padaiveera",
  "vaniyar padaiyachi",
  "vaniyar padaiyalai",
  "vaniyar padaiyannu",
  "vaniyar padaiyar",
  "vaniyar pallar",
  "vaniyar parayar",
  "vaniyar pillai",
  "vaniyar rathaamar",
  "vaniyar salavai",
  "vaniyar sathiriya",
  "vaniyar soleya",
  "vaniyar soliya",
  "vaniyar udaiyar",
  "vaniyar valayar",
  "vaniyar washerman",
  "vaniyar",
  "vellalar esai",
  "vellalar goundar",
  "vellalar isai",
  "vellalar karakadu",
  "vellalar karkathapillai",
  "vellalar karkathavellalar",
  "vellalar kurumbar",
  "vellalar kuyavar",
  "vellalar marameri",
  "vellalar padaiyachi",
  "vellalar padaiyalai",
  "vellalar pillai",
  "vellalar saiva",
  "vellalar soleya",
  "vellalar soliya",
  "vellalar soneya",
  "vellalar tholuva",
  "vellalar tholuvavellalar",
  "vellalar tulva",
  "vellalar turava",
  "vellalar veerakodai",
  "vellalar",
  "villiamudu nayakkar",
  "vishwakarma achary",
  "vishwakarma asari",
  "vishwakarma nadar",
  "yadav konar",
  "yadav",
  "yadavar ganar",
  "yadavar gonar",
  "yadavar konar",
  "yadavar yadavar",
  "yadavar",
  "others ",
];
